### ISSUE TITLE
Readme is WRONG and BAD

### ISSUE THREAD

**Issue by JJL772** [Demez/DemezProjectCreator#14]
hi, i tried to follow instructions on how to install lxml but it didnt work!!

i solved the issue by upgrading pip to latest, uninstalling lxml and then installing it again using `py -m pip install lxml`.

please fix the readme so i can do this right the first time and not have to use my brain!!!!

what if someone with 56 iq tried to use qpc? that would be a big problem, and they would not use qpc! at least 50% of the american population would not use qpc if the readme is this wrong!

**Comment by JJL772** [comment]
it's been 20 hours! why is this not fixed!!!!!!!!!!!!!!

**Comment by CoderSear** [comment]
MFW the

**Comment by JJL772** [comment]
closed because reasons
