### ISSUE TITLE
Feature Request: Implement "use_in_build" option

### ISSUE THREAD

**Issue by CoderSear** [Demez/DemezProjectCreator#7]
Should be true by default. Example:
```
"file1.cpp" \
"file2.cpp" \
"*.cxx"
{
    use_in_build "false"
}

"otherfile"
{
    use_in_build "false"
}
```

For makefiles and compile_commands this should effectively ignore the file(s) during generation. For Visual Studio projects and potential future IDE projects, this should add the file to the project, but should mark it as excluded from build. The use case for this is so that you can files included in your IDE that you want to edit but want to be compiled by something other than the IDE's C++ compiler (say, if you wanted to edit a shader in the IDE, but you want to build the shader with a custom pre_build build_event).

**Comment by Demez** [comment]
could use_in_build be compile?

also compile would only work on source files, based on file extension

**Comment by CoderSear** [comment]
`compile` would also be a good name, yeah. Can you elaborate more on what you mean by it being based off of extension?

**Comment by Demez** [comment]
when adding a file, it checks if the file extension is in a set of source file extensions. If it is, it adds it in a source_files dict, with all the values being a `SourceFile` object, which only stores a folder path for editors like visual studio, and a `Compiler` object, which is the same one used in configuration. But if it doesn't match that file extension, it's added into a files dict, with all the values being the editor folder path, and thus not allowing the `compile` option to be used there.

It could be better tbh

**Comment by Demez** [comment]
the code for this is located here if you want to look: https://github.com/quiverteam/QuiverProjectCreator/blob/master/qpc_project.py#L206

**Comment by CoderSear** [comment]
Alright. So if you add a file with an extension that doesn't match a source extension, it will show up in the project listing in the IDE but will be marked as excluded from build, right? In that case, any source file with `compile "false"` should just be sent down that code path.

**Comment by Demez** [comment]
That would work. A key like `-` might be neater though, less typing and code, but it would most likely be unclear as to what the key does, so i'll just stick with `compile "false"`

**Comment by CoderSear** [comment]
Isn't `-` already used to explicitly remove files from the file list?

**Comment by Demez** [comment]
Yeah, im just bringing it up as an example of a special key type, `folder` is kind of like a special key as well

**Comment by CoderSear** [comment]
Ah yeah -- I missed the `-`. New question -- should it be like this:
```
"file1.cpp" \
"file2.cpp" \
"*.cxx"
{
    use_in_build "false"
}
```

or like this?

```
"file1.cpp" \
"file2.cpp" \
"*.cxx"
{
    configuration 
    {
          use_in_build "false"
    }
}
```

or something else?

**Comment by Demez** [comment]
Probably the first one, less typing

**Comment by Demez** [comment]
Done in https://github.com/quiverteam/QuiverProjectCreator/commit/480d7dc44ad84e80ad3e0c879c2925cef523b096

**Comment by CoderSear** [comment]
For future reference: `use_in_build` was renamed to `build`
