### ISSUE TITLE
Feature Request: Re-work build events

### ISSUE THREAD

**Issue by CoderSear** [Demez/DemezProjectCreator#8]
Here is the current syntax:
```
// "declaring", name, arguments defined as macros locally
build_event "run_moc" "file"
{
    pre_build
    {
        "moc.exe -v $FILE" [$WINDOWS]
        "./moc $FILE" [$LINUX]
    }
}

build_event "2params" "file" "value"
{
    post_build
    {
        "2params.exe -v $FILE -D$VALUE" [$WINDOWS]
        "./2params $FILE -D$VALUE" [$LINUX]
    }
}

// using it
build_event "run_moc" "foo.hmoc"
build_event "run_moc" "bar.hmoc"

build_event "2params" "testFile.p2" "_CRT_SECURE_NO_DEPRECATE"
```

Here is the proposed syntax:
```
// The entries after the event name (in this case, run_moc) are parameter names.
build_event run_moc "file"
{
         // We no longer care about pre_build, post_build, etc events within
         // the event itself; the event is essentially just a function, and 
         // the pre_build, post_build, post_link, and cleanup events
         // effectively "call" this event.
        "moc.exe -v $FILE" [$WINDOWS]
        "./moc $FILE" [$LINUX]
}

// This syntax is the name of an event type and the corresponding event to call.
// The valid events are: pre_build, post_build, post_link, and cleanup
// Let's call this the "file list" call because it's called with a file list
pre_build run_moc 
{
    "foo.moc"
    "bar.moc"
     // Note that this bracket syntax supports wildcards -- 
     // it should be treated the same as QPC file syntax.
    "*.moc_new"
}

// If you call this with a direct literal, it won't try to expand the wildcard
// to match files in the directory -- it will literally pass in *.mod_old.
// Let's call this the "direct literal" call
pre_build run_moc "*.moc_old"

// Here is a build event that takes multiple parameters:
build_event "2params" "file" "value"
{
   "2params.exe -v $FILE -D$VALUE" [$WINDOWS]
   "./2params $FILE -D$VALUE" [$LINUX]
}

// Note that you CAN'T use bracket syntax for events with multiple parameters.
// Each argument is interpreted literally because it is a direct literal call.
post_build "2params" "testFile.p2" "_CRT_SECURE_NO_DEPRECATE"
```

Some things to be noted/resolved:
* I've proposed two new new event types called `post_link` (self-explanatory) and `cleanup`. The `cleanup` event will ALWAYS be run after the build/link "finishes", regardless of whether the build & link failed or succeeded. I'm not sure what the current behavior of `post_build` is, but it should ideally be changed to only run after a *successful* build. Similarly, `post_link` should only be ran after a successful link. I've removed `pre_link` because it's the same as the new `post_build`.
* Where should the build event definitions and "calls" go? Demez, you proposed putting this in the `configuration` block. I'm not well-versed enough in QPC to offer a legitimate opinion here, but that logically makes sense to me. 
* Should the param names be case-sensitive, or forced uppercase, or what? I just copied your example for mine.

**Comment by Demez** [comment]
- `post_link` would work fine here, took me a minute to fully understand what you meant with the changes, `post_build` would go to Pre-Link Event in VStudio, and `post_link` would go to Post-Build Event in VStudio
- The param names are case-sensitive, macros can actually be defined in whatever casing you wanted, uppercase is just what valve used for macros
- The `pre_build` stuff is already in `configuration`, build_event's themselves are defined and called in the root of the script currently, they should probably stay defined outside of configuration, as im not sure how I would neatly put build event definitions into the code for configurations

also, here's another idea for calling build_events with another idea:
```
pre_build
{
    // build events are now called here
    build_event run_moc
    {
        "foo.moc"
        "bar.moc"
         // Note that this bracket syntax supports wildcards -- 
         // it should be treated the same as QPC file syntax.
        "*.moc_new"
    }
    
    // multiple parameter call
    build_event "2params" "testFile.p2" "_CRT_SECURE_NO_DEPRECATE"
    
    // swissChili (or fidel cashflow) was talking about this in discord recently
    // this would allow you to call install scripts, like in cmake
    // according to swissChili, this uses make install or a batch script to install it
    // im assuming i might need more stuff than just this in that case
    install
    {
        foobar
    }
    
    command
    {
        "echo stuff"
    }
}
```

**Comment by CoderSear** [comment]
Firstly, I really like the idea of an install functionality -- but I don't think it should be done with its own syntax, and I'm failing to understand what advantages this new design has over the prior proposed one. We could probably just add `install` as an additional event, like `cleanup` and `pre_build`. 

I'll elaborate more on why I think that second proposed syntax isn't really better. With the syntax in my original comment syntax -- notwithstanding the inclusion of `cleanup` as a new event -- it would look like this:
```
pre_build run_moc
{
    "foo.moc"
    "bar.moc"
    "*.moc_new"
}
pre_build "2params" "testFile.p2" "_CRT_SECURE_NO_DEPRECATE"
pre_build command "echo stuff" // runs echo stuff -- this assumes theres a build event called command defined. Could be a built-in, maybe, or in a base script.
install foobar // In your example this was in the pre_build block. How would that work?
// It doesn't make sense to have a pre-build install step imo, since a build wouldn't always/ever
// occur during an installation anyways. When you do "make install", it doesn't typically build
// the project as well, does it? That's why I think install should be it's own build event.
```

Issue 1 with your proposed syntax: You're using `build_event` to call the build event it seems, even though it would already be used to *define* the event, causing syntax confusion. Even if the two are used exclusively in different scopes, it would still be confusing. Imagine if `for` in C++ could mean different things depending on the context.

Issue 2: Why the unnecessary "hardcoding" of `install` and `command`? It would be incredibly easy to abstract `command` into a build event, as I've noted in the code comments. As I've also noted in the comments, `install` can be abstracted into another build event. 

Issue 3: It doesn't really seem to make much stuff easier. I do see the value in allowing for a pre_build **block**, but I don't think such a block should be mandatory, and it may as well interpret all the values inside it -- `run_moc`, `2params`, `command` -- as build events anyways.

Taking that all into account, here's my new proposed syntax, working off of some of the ideas you've expressed in yours:

```
// The entries after the event name (in this case, run_moc) are parameter names.
build_event run_moc "file"
{
         // We no longer care about pre_build, post_build, etc events within
         // the event itself; the event is essentially just a function, and 
         // the pre_build, post_build, post_link, and cleanup events
         // effectively "call" this event.
        "moc.exe -v $FILE" [$WINDOWS]
        "./moc $FILE" [$LINUX]
}

// This syntax is the name of an event type and the corresponding event to call.
// The valid events are: pre_build, post_build, post_link, cleanup, and install
// Let's call this the "file list" call because it's called with a file list
pre_build run_moc 
{
    "foo.moc"
    "bar.moc"
     // Note that this bracket syntax supports wildcards -- 
     // it should be treated the same as QPC file syntax.
    "*.moc_new"
}

// If you call this with a direct literal, it won't try to expand the wildcard
// to match files in the directory -- it will literally pass in *.mod_old.
// Let's call this the "direct literal" call
pre_build run_moc "*.moc_old"

// Now let's call them in a block:
pre_build
{
    // Within the block the event type is implied so all we must do is type the
    // event name (in this case, run_moc) and the rest of the syntax is normal.

    run_moc
    {
        "oof.moc2"
        "rab.moc2"
    }
    run_moc "final.moc2"
}
// Here is a build event that takes multiple parameters:
build_event "2params" "file" "value"
{
   "2params.exe -v $FILE -D$VALUE" [$WINDOWS]
   "./2params $FILE -D$VALUE" [$LINUX]
}

// Note that you CAN'T use bracket syntax for events with multiple parameters.
// Each argument is interpreted literally because it is a direct literal call.
post_build "2params" "testFile.p2" "_CRT_SECURE_NO_DEPRECATE"

// Here is the implementation of your command idea
build_event "command" "input"
{
    "$INPUT"
}

pre_build command "echo stuff"

// This will be run in an install step
install command "echo Installing..."
```

However, I feel we should nail down the event syntax first *before* we move onto considering installation, or at least before we try integrating the install step into the build event system.

**Comment by CoderSear** [comment]
Also -
> post_link would work fine here, took me a minute to fully understand what you meant with the changes, post_build would go to Pre-Link Event in VStudio, and post_link would go to Post-Build Event in VStudio

I did not realize that you were already mirroring existing values. Disregard my comments about renaming the parameters.

**Comment by CoderSear** [comment]
(Half-Life 1 Scientist) Everything... seems to be in order.
