### ISSUE TITLE
Option Renaming

### ISSUE THREAD

**Issue by Demez** [Demez/DemezProjectCreator#9]
Some shorter name ideas, for less typing:
```
compiler {} -> compile {} (the group)
linker {}   -> link {}

preprocessor_definitions {} -> defines {}
include_directories {} -> inc_dirs {}
library_directories {} -> lib_dirs {}

configuration_type -> config_type or target

precompiled_header -> pch
precompiled_header_file -> pch_file
precompiled_header_output_file -> pch_out

default_include_directories -> default_inc_dirs
default_library_directories -> default_lib_dirs

import_library -> import_lib
ignore_import_library -> ignore_import_lib

libraries {} -> libs {}
ignore_libraries {} -> ignore_libs {}

dependencies {} -> depends {}
dependency_paths {} -> deleted, and projects would only allow for one script (redesign idea in mind for base scripts)
```

**Comment by CoderSear** [comment]
All look great, except perhaps the new name for `dependencies` should be `deps`? Maybe that's too short. `depends` is still a good name.

**Comment by CoderSear** [comment]
On second thought, I think that `dependencies` is fine as-is.

**Comment by Demez** [comment]
wouldn't make sense to rename `configuration` to `config`, and leave that as is, still thinking depends or deps is good

**Comment by CoderSear** [comment]
what about `requires` instead of `dependencies`? It's short and also pretty clear

**Comment by Demez** [comment]
`requires` would be nice

with this renaming, should I even bother to support the older names as legacy options, and throw a warning when used, even though it would be slightly messy?

the renaming would be done on a separate branch from upcoming, then I would make a script updater, and update a lot of scripts to these new names.

**Comment by Demez** [comment]
also, would `config_type` or `target` be better for replacing `configuration_type`?

**Comment by Demez** [comment]
I've started renaming these options on this branch here: https://github.com/quiverteam/QuiverProjectCreator/tree/rename
on hold for ninja support (and maybe some other things), but after I have a reliable script updater to update qpc scripts from the old names to the new names, it will be on upcoming (and maybe even master soon)

**Comment by Demez** [comment]
This has been done on the rename branch, which is basically the new upcoming branch at this point lol
